id: PB6643937
initial_creation_type: input
source_metadata:
  title: Ngulchu Dharmabhadra Series
  language: en
  description: 'A series of texts by and about the great Gelugpa scholar Ngulchu Dharmabhadra
    (dngul chu dharma bhadra, 1771–1852):'
  volume:
    0cf04c826133415e8e763e2860680c6b:
      title: Method of Confession based on the Four Powers
      parent: Confession
    df3ac7ac979a40a187dd0b98c4d5af0a:
      title: Concise Explanatory Outline of the Heart of Wisdom
      parent: Prajñāpāramitā
created_at: '2022-03-01T01:02:04.201149'
last_modified_at: '2022-03-01T01:02:04.201155'
